# Generated by Django 5.2.7 on 2025-11-09 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        ("teams", "0003_team_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=64)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={"ordering": ["-start_date"]},
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role_on_team", models.CharField(choices=[("PLAYER","Player"),("COACH","Coach"),("STAFF","Staff")], max_length=10)),
                ("jersey_number", models.PositiveIntegerField(blank=True, null=True)),
                ("squad_status", models.CharField(blank=True, max_length=32)),
                ("active", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
        ),
        # ⚠️ removed AddConstraint(head_coach_must_be_coach) — not valid in DB-level CHECK
        migrations.AddField(
            model_name="teammembership",
            name="primary_position",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_memberships", to="profiles.position"
            ),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="season",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name="memberships", to="teams.season"
            ),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="secondary_positions",
            field=models.ManyToManyField(blank=True, related_name="secondary_memberships", to="profiles.position"),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="team",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="teams.team"),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(fields=["team","role_on_team","active"], name="teams_teamm_team_id_2f646f_idx"),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(fields=["user","team"], name="teams_teamm_user_id_df7167_idx"),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("jersey_number__isnull", False)),
                fields=("team","season","jersey_number"),
                name="uniq_team_season_jersey",
            ),
        ),
    ]
