# Generated by Django 5.2.7 on 2025-11-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_seed_positions"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachprofile",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
