# Generated by Django 5.2.7 on 2025-11-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="jersey_number",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="position",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="team",
        ),
    ]
