# Generated by Django 5.2.7 on 2025-11-09 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ["COACH", "STAFF", "ADMIN"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
